### ISSUE TITLE
SNAP: ModuleNotFoundError: No module named 'cv2'

### ISSUE THREAD

**Issue by sysdef** [OpenDroneMap/ODM#1438]
_This error was ignored in http://community.opendronemap.org/c/opendronemap so I open an issue here_ 

```
$ sudo /snap/bin/opendronemap 
Python path configuration:
  PYTHONHOME = (not set)
  PYTHONPATH = (not set)
  program name = 'python3'
  isolated = 0
  environment = 1
  user site = 1
  import site = 1
  sys._base_executable = '/usr/bin/python3'
  sys.base_prefix = '/usr'
  sys.base_exec_prefix = '/usr'
  sys.executable = '/usr/bin/python3'
  sys.prefix = '/usr'
  sys.exec_prefix = '/usr'
  sys.path = [
    '/usr/lib/python38.zip',
    '/usr/lib/python3.8',
    '/usr/lib/python3.8/lib-dynload',
  ]
Fatal Python error: init_fs_encoding: failed to get the Python codec of the filesystem encoding
Python runtime state: core initialized
ModuleNotFoundError: No module named 'encodings'

Current thread 0x00007f66cf4d6740 (most recent call first):
<no Python frame>
```
```
$ uname -a; cat /etc/debian_version 
Linux can 5.10.0-12-amd64 #1 SMP Debian 5.10.103-1 (2022-03-07) x86_64 GNU/Linux
11.2
```

**Comment by pierotofy** [comment]
Thanks for reporting the issue!

Currently our snap image hasn't been updated in a while due a build issue with https://github.com/diddlesnaps/snapcraft-container/issues/8 (not sure if this is related, but it could be).

**Comment by Camilochiang** [comment]
Til today, August 9, this problem persist.

**Comment by lucyllewy** [comment]
Hi, @pierotofy , I have good news, I believe I've fixed the container image so you can re-enable the snap build.

**Comment by pierotofy** [comment]
Thanks @diddledani ! 🙏 I've seen the changes in the container image, but haven't tested it. I will sometimes this weekend (unless somebody beats me to it).

**Comment by pierotofy** [comment]
It built! 🎉

**Comment by JeroenDelcour** [comment]
I'm still getting the same `No module named 'encodings'` error on a fresh install through snap. I see the snap image has been updated yesterday so I assumed the fixed version had been deployed. Am I missing something?

**Comment by JeroenDelcour** [comment]
Thanks for the fix, but it seems the [snap publishing pipeline is broken](https://github.com/OpenDroneMap/ODM/runs/8079544892?check_suite_focus=true) so I'm unable to test it.

**Comment by pierotofy** [comment]
Mm, something else seems to be breaking the build, as you pointed out. I'm not sure of the cause.

**Comment by pierotofy** [comment]
I made some changes, which seemed to have worked (?) https://github.com/OpenDroneMap/ODM/runs/8210390371?check_suite_focus=true

I haven't tested as I don't have snap installed locally.

**Comment by lucyllewy** [comment]
oh yes, that was my bad. I forgot to remove the `part` that tries to use `snap/local` after removing all the files from the directory. Well done, you made the correct fix that I would have if I had got here earlier :-)

**Comment by JeroenDelcour** [comment]
Thanks for the fix! The `No module named 'encodings'` error seems fixed. However, I'm now getting another missing dependency:

```
Traceback (most recent call last):
  File "/snap/opendronemap/177/odm/run.py", line 15, in <module>
    from opendm.utils import get_processing_results_paths, rm_r
  File "/snap/opendronemap/177/odm/opendm/utils.py", line 3, in <module>
    from opendm.photo import find_largest_photo_dims
  File "/snap/opendronemap/177/odm/opendm/photo.py", line 17, in <module>
    from opendm import get_image_size
  File "/snap/opendronemap/177/odm/opendm/get_image_size.py", line 2, in <module>
    import cv2
ModuleNotFoundError: No module named 'cv2'
```

Should I make a new issue for this?

**Comment by ArthurTlprt** [comment]
Same issue than @JeroenDelcour after installing ODM via snap on Ubuntu 21.

**Comment by pierotofy** [comment]
No need for a new issue. Mm, something is still broken. Probably a PYTHONPATH issue or the cv2 module not being included in the snap package.

**Comment by pierotofy** [comment]
One more attempt: https://github.com/OpenDroneMap/ODM/commit/081d4c89487137512b8f3b0e84c4acf39625af84

**Comment by pierotofy** [comment]
I will assume this has been solved, if not please feel free to re-open? 🙏

**Comment by JeroenDelcour** [comment]
It has not been solved. Updating the snap package and running `opendronemap` without any arguments still shows the same error. Have you tested your own commit? Are you not getting this error?

You can leave it closed if you like, I'm personally not going to put more time into this. I rely on opendronemap in a production setting, so until the snap release gets better testing to show its reliable, I'm going to stick to the Docker image.

**Comment by pierotofy** [comment]
I unfortunately don't have an Ubuntu machine to test this on.

I will also stop putting more time into this; I don't use snap and this will have to wait for a community fix.

**Comment by pierotofy** [comment]
Fixed and tested with https://github.com/OpenDroneMap/ODM/commit/61d1865bd3a522106461b8a9d754039eaa122ecc and https://github.com/OpenDroneMap/ODM/commit/093929dd914ee56fbfe6016769eb0bdaa1e62fbf

**Comment by sysdef** [comment]
Thank you for fixing that!

**Comment by JeroenDelcour** [comment]
Thanks for fixing!

It took me a minute to figure out how to use it, so for anyone else wondering: it expects an absolute file path, rather than relative to the present working directory.
