### ISSUE TITLE
ImportError: libecto.so.0.6: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by thierrydecae** [OpenDroneMap/ODM#334]
Hi, 
I would really appreciate some help please. I'm trying to run ODM on a few pictures that I want to stitch together. My 'images' folder is in /home/ubuntu/OpenDroneMap/ so I run the following command from the /home/ubuntu/OpenDroneMap/ folder  
python run.py --project-path /home/ubuntu/OpenDroneMap

but i get the following error:

ubuntu@drone-image-processing:~/OpenDroneMap$ python run.py --project-path /home/ubuntu/OpenDroneMap
[INFO]    Initializing OpenDroneMap app - Fri Jul 08 13:10:05  2016
[INFO]    Running ODM Load Dataset Cell
[DEBUG]   Loading dataset from: /home/ubuntu/OpenDroneMap/images
Traceback (most recent call last):
  File "run.py", line 38, in <module>
    plasm.execute(niter=1)
  File "/home/ubuntu/OpenDroneMap/scripts/dataset.py", line 57, in process
    self.params.force_ccd)
  File "/home/ubuntu/OpenDroneMap/opendm/types.py", line 32, in **init**
    self.parse_pyexiv2_values(self.path_file, force_focal, force_ccd)
  File "/home/ubuntu/OpenDroneMap/opendm/types.py", line 73, in parse_pyexiv2_values
    self.make_model = sensor_string(self.camera_make, self.camera_model)
  File "/home/ubuntu/OpenDroneMap/SuperBuild/src/opensfm/opensfm/exif.py", line 63, in sensor_string
    model = model.replace(make, '') # remove possible duplicate 'make' information in 'model' for better matching
AttributeError: 'NoneType' object has no attribute 'replace'
ubuntu@drone-image-processing:~/OpenDroneMap$

when i try with 'run.sh' I get the following error:

ubuntu@drone-image-processing:~/OpenDroneMap$ ./run.sh --project-path /home/ubuntu/OpenDroneMap
[INFO]    Initializing OpenDroneMap app - Fri Jul 08 13:28:02  2016
[INFO]    Running ODM Load Dataset Cell
[DEBUG]   Loading dataset from: /home/ubuntu/OpenDroneMap/images
Traceback (most recent call last):
  File "/home/ubuntu/OpenDroneMap/run.py", line 38, in <module>
    plasm.execute(niter=1)
  File "/home/ubuntu/OpenDroneMap/scripts/dataset.py", line 57, in process
    self.params.force_ccd)
  File "/home/ubuntu/OpenDroneMap/opendm/types.py", line 32, in **init**
    self.parse_pyexiv2_values(self.path_file, force_focal, force_ccd)
  File "/home/ubuntu/OpenDroneMap/opendm/types.py", line 73, in parse_pyexiv2_values
    self.make_model = sensor_string(self.camera_make, self.camera_model)
  File "/home/ubuntu/OpenDroneMap/SuperBuild/src/opensfm/opensfm/exif.py", line 63, in sensor_string
    model = model.replace(make, '') # remove possible duplicate 'make' information in 'model' for better matching
AttributeError: 'NoneType' object has no attribute 'replace'

if anyone can help me it would be much appreciated.

Thank you

**Comment by dakotabenjamin** [comment]
Ach sorry this was a problem I meant to fix earlier. It's actually a really simple solution, I just haven't had any time to dedicate to it. You could easily fix it yourself:

On line 30 of `opendm/types.py` it now shows this:

```
        self.make_model = None
```

Replace `None` with `''`: (two single apostrophes)

```
        self.make_model = ''
```

**Comment by thierrydecae** [comment]
Hi,
Thank you for your help and making this wonderful project also. I will try this fix early next week when back in office.
Best regards
Thierry

Sent from BlueMailhttp://www.bluemail.me/r

On 8 Jul 2016, at 17:13, Dakota Benjamin <notifications@github.com<mailto:notifications@github.com>> wrote:

Ach sorry this was a problem I meant to fix earlier. It's actually a really simple solution, I just haven't had any time to dedicate to it. You could easily fix it yourself:

On line 30 of opendm/types.py it now shows this:

```
    self.make_model = None
```

Replace None with '': (two single apostrophes)

```
    self.make_model = ''
```

**Comment by fahmiroi** [comment]
Hi,

Replacing None with ' ' didn't solve the problem for me. :(

Still have the same error message..

@tdecae : what about you?

**Comment by dakotabenjamin** [comment]
In #348 I have fixed this problem, I believe. Can you test for me?

```
git checkout -b dakotabenjamin-odmphoto_fix dev
git pull https://github.com/dakotabenjamin/OpenDroneMap.git odmphoto_fix
```

If you using the `dev` branch already, you will not have to rerun the installation procedures. If you do not have the `dev` branch installed, you may have to checkout dev first, then do the above, then run through the installation procedures.

**Comment by fahmiroi** [comment]
It worked ! The problem is solved and the processing of my data set ist running :)

Many Thanks !!

**Comment by dakotabenjamin** [comment]
Great news!

@tdecae would love if you tested as well.

**Comment by troymyname** [comment]
@dakotabenjamin I am still getting the error. The _self.make_model =_ is already set to two single apostrophes. I would really appreciate it if you can help please.

**Comment by dakotabenjamin** [comment]
I'm sorry to hear that @troymyname. Are you using the latest release? [v0.2](https://github.com/OpenDroneMap/OpenDroneMap/releases/tag/v0.2)

**Comment by troymyname** [comment]
Hi, yes. I am using Version 0.2. Thanks for responding!

**Comment by dakotabenjamin** [comment]
Can you post the error message you are getting, along with other relevant info, like project setup, etc?

**Comment by troymyname** [comment]
@dakotabenjamin I have opened up issue #480.
